### ISSUE TITLE
Issue in importing lib

### ISSUE THREAD

**Issue by gabrielpeixoto-cvai** [marximus/dense-trajectory#5]
I compiled the library with make, but when I try to use it in python I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vntgaca/git_repos/dense-trajectory/densetrack.py", line 20, in <module>
    _densetrack = _lib.densetrack
  File "/usr/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/vntgaca/git_repos/dense-trajectory/dense_trajectory_release_v1.2/release/DenseTrack.so: undefined symbol: densetrack

**Comment by zijieli-Jlee** [comment]
Got same error here, and I am using Python 3.5. Is there any solution on this? Thanks in advance.
